-- Роли
create table roles (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    description varchar(255)
);

-- Пользователи
create table users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null,
    email varchar(255)
);

-- Таблица связей пользователей и ролей
create table users_roles (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id),
    foreign key (role_id) references roles (id),
    foreign key (user_id) references users (id)
);

-- Счета
create table accounts (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    amount numeric(38,2),
    creation date not null,
    user_id bigint,
    foreign key (user_id) references users (id)
);
